print("*****************************************************")
print("************ Caixa Eletrônico - MQS *****************")
print("*****************************************************")
account_typed = input("Insira sua Conta: ")
password_typed = input("Insira sua Senha: ")
print(account_typed)
print(password_typed)
print("*****************************************************")
print("*****************************************************")
